// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AnyWorkflowRunStep any workflow run step
// swagger:model AnyWorkflowRunStep
type AnyWorkflowRunStep struct {

	// Time at which the step execution ended
	// Format: date-time
	EndedAt *strfmt.DateTime `json:"ended_at,omitempty"`

	// Time at which step execution started
	// Format: date-time
	StartedAt *strfmt.DateTime `json:"started_at,omitempty"`

	// Workflow run step status
	// Required: true
	// Enum: [success failure in-progress pending]
	Status *string `json:"status"`
}

// Validate validates this any workflow run step
func (m *AnyWorkflowRunStep) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEndedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStartedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AnyWorkflowRunStep) validateEndedAt(formats strfmt.Registry) error {

	if swag.IsZero(m.EndedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("ended_at", "body", "date-time", m.EndedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *AnyWorkflowRunStep) validateStartedAt(formats strfmt.Registry) error {

	if swag.IsZero(m.StartedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("started_at", "body", "date-time", m.StartedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

var anyWorkflowRunStepTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["success","failure","in-progress","pending"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		anyWorkflowRunStepTypeStatusPropEnum = append(anyWorkflowRunStepTypeStatusPropEnum, v)
	}
}

const (

	// AnyWorkflowRunStepStatusSuccess captures enum value "success"
	AnyWorkflowRunStepStatusSuccess string = "success"

	// AnyWorkflowRunStepStatusFailure captures enum value "failure"
	AnyWorkflowRunStepStatusFailure string = "failure"

	// AnyWorkflowRunStepStatusInProgress captures enum value "in-progress"
	AnyWorkflowRunStepStatusInProgress string = "in-progress"

	// AnyWorkflowRunStepStatusPending captures enum value "pending"
	AnyWorkflowRunStepStatusPending string = "pending"
)

// prop value enum
func (m *AnyWorkflowRunStep) validateStatusEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, anyWorkflowRunStepTypeStatusPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *AnyWorkflowRunStep) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", *m.Status); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AnyWorkflowRunStep) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AnyWorkflowRunStep) UnmarshalBinary(b []byte) error {
	var res AnyWorkflowRunStep
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
