// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ApprovalWorkflowRunStep approval workflow run step
// swagger:model ApprovalWorkflowRunStep
type ApprovalWorkflowRunStep struct {
	AnyWorkflowRunStep

	ApprovalWorkflowStep

	// Workflow run step approval for manual gates
	// Enum: [waiting rejected approved]
	Approval *string `json:"approval,omitempty"`

	// Time at which the step was approved or rejected
	// Format: date-time
	ApprovalSubmittedAt *strfmt.DateTime `json:"approval_submitted_at,omitempty"`

	// approver
	Approver *UserSummary `json:"approver,omitempty"`

	// Type of step
	// Required: true
	// Enum: [approval]
	Type *string `json:"type"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ApprovalWorkflowRunStep) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 AnyWorkflowRunStep
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.AnyWorkflowRunStep = aO0

	// AO1
	var aO1 ApprovalWorkflowStep
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.ApprovalWorkflowStep = aO1

	// AO2
	var dataAO2 struct {
		Approval *string `json:"approval,omitempty"`

		ApprovalSubmittedAt *strfmt.DateTime `json:"approval_submitted_at,omitempty"`

		Approver *UserSummary `json:"approver,omitempty"`

		Type *string `json:"type"`
	}
	if err := swag.ReadJSON(raw, &dataAO2); err != nil {
		return err
	}

	m.Approval = dataAO2.Approval

	m.ApprovalSubmittedAt = dataAO2.ApprovalSubmittedAt

	m.Approver = dataAO2.Approver

	m.Type = dataAO2.Type

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ApprovalWorkflowRunStep) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 3)

	aO0, err := swag.WriteJSON(m.AnyWorkflowRunStep)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.ApprovalWorkflowStep)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	var dataAO2 struct {
		Approval *string `json:"approval,omitempty"`

		ApprovalSubmittedAt *strfmt.DateTime `json:"approval_submitted_at,omitempty"`

		Approver *UserSummary `json:"approver,omitempty"`

		Type *string `json:"type"`
	}

	dataAO2.Approval = m.Approval

	dataAO2.ApprovalSubmittedAt = m.ApprovalSubmittedAt

	dataAO2.Approver = m.Approver

	dataAO2.Type = m.Type

	jsonDataAO2, errAO2 := swag.WriteJSON(dataAO2)
	if errAO2 != nil {
		return nil, errAO2
	}
	_parts = append(_parts, jsonDataAO2)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this approval workflow run step
func (m *ApprovalWorkflowRunStep) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with AnyWorkflowRunStep
	if err := m.AnyWorkflowRunStep.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with ApprovalWorkflowStep
	if err := m.ApprovalWorkflowStep.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateApproval(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateApprovalSubmittedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateApprover(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var approvalWorkflowRunStepTypeApprovalPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["waiting","rejected","approved"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		approvalWorkflowRunStepTypeApprovalPropEnum = append(approvalWorkflowRunStepTypeApprovalPropEnum, v)
	}
}

// property enum
func (m *ApprovalWorkflowRunStep) validateApprovalEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, approvalWorkflowRunStepTypeApprovalPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *ApprovalWorkflowRunStep) validateApproval(formats strfmt.Registry) error {

	if swag.IsZero(m.Approval) { // not required
		return nil
	}

	// value enum
	if err := m.validateApprovalEnum("approval", "body", *m.Approval); err != nil {
		return err
	}

	return nil
}

func (m *ApprovalWorkflowRunStep) validateApprovalSubmittedAt(formats strfmt.Registry) error {

	if swag.IsZero(m.ApprovalSubmittedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("approval_submitted_at", "body", "date-time", m.ApprovalSubmittedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ApprovalWorkflowRunStep) validateApprover(formats strfmt.Registry) error {

	if swag.IsZero(m.Approver) { // not required
		return nil
	}

	if m.Approver != nil {
		if err := m.Approver.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("approver")
			}
			return err
		}
	}

	return nil
}

var approvalWorkflowRunStepTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["approval"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		approvalWorkflowRunStepTypeTypePropEnum = append(approvalWorkflowRunStepTypeTypePropEnum, v)
	}
}

// property enum
func (m *ApprovalWorkflowRunStep) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, approvalWorkflowRunStepTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *ApprovalWorkflowRunStep) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ApprovalWorkflowRunStep) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApprovalWorkflowRunStep) UnmarshalBinary(b []byte) error {
	var res ApprovalWorkflowRunStep
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
