// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ContainerWorkflowRunStep container workflow run step
// swagger:model ContainerWorkflowRunStep
type ContainerWorkflowRunStep struct {
	AnyWorkflowRunStep

	ContainerWorkflowStep

	// Type of step
	// Required: true
	// Enum: [container]
	Type *string `json:"type"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *ContainerWorkflowRunStep) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 AnyWorkflowRunStep
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.AnyWorkflowRunStep = aO0

	// AO1
	var aO1 ContainerWorkflowStep
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.ContainerWorkflowStep = aO1

	// AO2
	var dataAO2 struct {
		Type *string `json:"type"`
	}
	if err := swag.ReadJSON(raw, &dataAO2); err != nil {
		return err
	}

	m.Type = dataAO2.Type

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m ContainerWorkflowRunStep) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 3)

	aO0, err := swag.WriteJSON(m.AnyWorkflowRunStep)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.ContainerWorkflowStep)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	var dataAO2 struct {
		Type *string `json:"type"`
	}

	dataAO2.Type = m.Type

	jsonDataAO2, errAO2 := swag.WriteJSON(dataAO2)
	if errAO2 != nil {
		return nil, errAO2
	}
	_parts = append(_parts, jsonDataAO2)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this container workflow run step
func (m *ContainerWorkflowRunStep) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with AnyWorkflowRunStep
	if err := m.AnyWorkflowRunStep.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with ContainerWorkflowStep
	if err := m.ContainerWorkflowStep.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var containerWorkflowRunStepTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["container"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		containerWorkflowRunStepTypeTypePropEnum = append(containerWorkflowRunStepTypeTypePropEnum, v)
	}
}

// property enum
func (m *ContainerWorkflowRunStep) validateTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, containerWorkflowRunStepTypeTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *ContainerWorkflowRunStep) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ContainerWorkflowRunStep) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ContainerWorkflowRunStep) UnmarshalBinary(b []byte) error {
	var res ContainerWorkflowRunStep
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
