// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// EventSummary event summary
// swagger:model EventSummary
type EventSummary struct {
	EventIdentifier

	// source
	// Required: true
	Source *EventSourceIdentifier `json:"source"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *EventSummary) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 EventIdentifier
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.EventIdentifier = aO0

	// AO1
	var dataAO1 struct {
		Source *EventSourceIdentifier `json:"source"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.Source = dataAO1.Source

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m EventSummary) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.EventIdentifier)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	var dataAO1 struct {
		Source *EventSourceIdentifier `json:"source"`
	}

	dataAO1.Source = m.Source

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this event summary
func (m *EventSummary) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with EventIdentifier
	if err := m.EventIdentifier.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSource(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EventSummary) validateSource(formats strfmt.Registry) error {

	if err := validate.Required("source", "body", m.Source); err != nil {
		return err
	}

	if m.Source != nil {
		if err := m.Source.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("source")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *EventSummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EventSummary) UnmarshalBinary(b []byte) error {
	var res EventSummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
