// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// EventTypeSummary event type summary
// swagger:model EventTypeSummary
type EventTypeSummary struct {
	EventTypeIdentifier

	EventTypeSummaryAllOf1
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *EventTypeSummary) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 EventTypeIdentifier
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.EventTypeIdentifier = aO0

	// AO1
	var aO1 EventTypeSummaryAllOf1
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.EventTypeSummaryAllOf1 = aO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m EventTypeSummary) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.EventTypeIdentifier)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.EventTypeSummaryAllOf1)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this event type summary
func (m *EventTypeSummary) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with EventTypeIdentifier
	if err := m.EventTypeIdentifier.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with EventTypeSummaryAllOf1

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *EventTypeSummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EventTypeSummary) UnmarshalBinary(b []byte) error {
	var res EventTypeSummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// EventTypeSummaryAllOf1 A summary of an event type
// swagger:model EventTypeSummaryAllOf1
type EventTypeSummaryAllOf1 interface{}
