// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// EventTypeIdentifierString A unique identifier for an event type expressed as a string of the format <name>@<version>
//
// swagger:model EventTypeIdentifierString
type EventTypeIdentifierString string

// Validate validates this event type identifier string
func (m EventTypeIdentifierString) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Pattern("", "body", string(m), `^.+@.+$`); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
