// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// EventSourceSummary event source summary
// swagger:model EventSourceSummary
type EventSourceSummary struct {
	EventSourceIdentifier

	// type
	// Required: true
	Type *EventTypeIdentifier `json:"type"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *EventSourceSummary) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 EventSourceIdentifier
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.EventSourceIdentifier = aO0

	// AO1
	var dataAO1 struct {
		Type *EventTypeIdentifier `json:"type"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.Type = dataAO1.Type

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m EventSourceSummary) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.EventSourceIdentifier)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	var dataAO1 struct {
		Type *EventTypeIdentifier `json:"type"`
	}

	dataAO1.Type = m.Type

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this event source summary
func (m *EventSourceSummary) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with EventSourceIdentifier
	if err := m.EventSourceIdentifier.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EventSourceSummary) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	if m.Type != nil {
		if err := m.Type.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("type")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *EventSourceSummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EventSourceSummary) UnmarshalBinary(b []byte) error {
	var res EventSourceSummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
